version: '3.3'

services:
  flask:
    image: ripo4ek/itmo-task-flask-mongo:latest
    ports:
      - "8080:8080"
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 1
networks:
  appnet:
    driver: overlay
    attachable: true
    